# NumPy Tutorial
__By Anish Sachdeva__

In [2]:
# pip install numpy
import numpy as np

## The Basics

In [3]:
a = [1, 2, 3]
print(a)
print(type(a))

[1, 2, 3]
<class 'list'>


In [4]:
a = np.array(a)
print(a)
print(type(a))

[1 2 3]
<class 'numpy.ndarray'>


In [5]:
# We can also create arrays of different dimensions in numpy
b = np.array([[1, 2, 3], [4, 5, 6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [6]:
print(type(b))

<class 'numpy.ndarray'>


In [7]:
# we can see the dimension of any nump array using the .shape command
print(b.shape)

(2, 3)


In [9]:
a = np.array([1, 2, 3])
print(a.shape)

(3,)


## Creating arrays using `Numpy.random` package

In [24]:
r = np.random.randint(100, size=(4, 10))
print(r)

[[69 47 12 80 72 21 58 11 70 56]
 [28 70 59  6 96 75 87 23 86 95]
 [53 77 75 25 27 62 78 80 13 12]
 [46 78 45 35 55  7 18 75 94 49]]


In [27]:
r2 = np.random.rand(3, 4)
print(r2)

[[0.91474156 0.59824563 0.61696441 0.87449874]
 [0.38074045 0.56002924 0.76406143 0.28856025]
 [0.8152455  0.2134286  0.42343823 0.82897078]]


## Accessing Specific Elements

In [28]:
r = np.random.randint(10, size=(3, 4))
print(r)

[[5 7 0 3]
 [5 6 0 5]
 [1 5 3 4]]


In [31]:
# accessing first row
print(r[0, ])

[5 7 0 3]


In [30]:
# accessing last row
print(r[-1, ])

[1 5 3 4]


In [32]:
# accessing specific row
row = 2
print(r[row - 1, ])

[5 6 0 5]


In [37]:
# accessing the first column
print(r[:, 0])

[5 5 1]


In [39]:
# accessing the last column and reshaping it into a column vector
c1 = r[:, 0]
print(c1)
c1 = c1.reshape((3, 1))
print(c1)

[5 5 1]
[[5]
 [5]
 [1]]


In [40]:
# accessing the last column
c2 = r[:, -1]
print(c2)

[3 5 4]


In [42]:
# reshaping the last column into column vector
c2 = c2.reshape((3, 1))
print(c2)

[[3]
 [5]
 [4]]


In [52]:
# retreiving specific rows
r = np.random.randint(low=0, high=100, size=(5, 6))
print(r)

[[68 21 79 25 80 11]
 [73 41 29 84 50 83]
 [86 15 65 40 97 55]
 [25 99  4 52 65 95]
 [22  6 87 98 76 84]]


In [53]:
print(r[[0, 1], :])

[[68 21 79 25 80 11]
 [73 41 29 84 50 83]]


In [54]:
# printing selected rows
print(r[[0, 3], ])

[[68 21 79 25 80 11]
 [25 99  4 52 65 95]]


In [55]:
# changing order of rows
print(r[[3, 0, 4], ])

[[25 99  4 52 65 95]
 [68 21 79 25 80 11]
 [22  6 87 98 76 84]]


In [58]:
# getting specific columns
print(r[:, [4, 2]])

[[80 79]
 [50 29]
 [97 65]
 [65  4]
 [76 87]]


In [59]:
# selecting a specific element (row, column)
print(r[0, 0])

68


In [60]:
row, column = 2, 3
print(r[row, column])

40


Getting elements using start, stop, step size (getting crazy 🙃) 

In [62]:
print(r)

[[68 21 79 25 80 11]
 [73 41 29 84 50 83]
 [86 15 65 40 97 55]
 [25 99  4 52 65 95]
 [22  6 87 98 76 84]]


In [63]:
print(r[::2, :])

[[68 21 79 25 80 11]
 [86 15 65 40 97 55]
 [22  6 87 98 76 84]]


In [64]:
print(r[::-1, ])

[[22  6 87 98 76 84]
 [25 99  4 52 65 95]
 [86 15 65 40 97 55]
 [73 41 29 84 50 83]
 [68 21 79 25 80 11]]


In [65]:
print(r[::-1, ::-1])

[[84 76 98 87  6 22]
 [95 65 52  4 99 25]
 [55 97 40 65 15 86]
 [83 50 84 29 41 73]
 [11 80 25 79 21 68]]


In [66]:
print(r[1:4:2, 0:5:3])

[[73 84]
 [25 52]]


## Changing the Value of the matrices

In [67]:
print(r)

[[68 21 79 25 80 11]
 [73 41 29 84 50 83]
 [86 15 65 40 97 55]
 [25 99  4 52 65 95]
 [22  6 87 98 76 84]]


In [68]:
#changing the value of a single element
r[0, 0] = 100
print(r)

[[100  21  79  25  80  11]
 [ 73  41  29  84  50  83]
 [ 86  15  65  40  97  55]
 [ 25  99   4  52  65  95]
 [ 22   6  87  98  76  84]]


In [69]:
# changing the value of an entire row
r[0, :] = np.random.randint(low=-100, high=0, size=(1, 6))
print(r)

[[-73 -43 -55 -28 -56 -91]
 [ 73  41  29  84  50  83]
 [ 86  15  65  40  97  55]
 [ 25  99   4  52  65  95]
 [ 22   6  87  98  76  84]]


In [73]:
# changing the value of an entire column 
r[:, [2]] = np.random.randint(low=-200, high=-100, size=(5, 1))
print(r)

[[ -73  -43 -151  -28  -56  -91]
 [  73   41 -106   84   50   83]
 [  86   15 -148   40   97   55]
 [  25   99 -131   52   65   95]
 [  22    6 -157   98   76   84]]


In [74]:
# changing the value of some particular elements
r[1, [0, 2]] = [0, 0]
print(r)

[[ -73  -43 -151  -28  -56  -91]
 [   0   41    0   84   50   83]
 [  86   15 -148   40   97   55]
 [  25   99 -131   52   65   95]
 [  22    6 -157   98   76   84]]


## Different Initialization Methods

In [76]:
# Creating the zeros Matrix
z = np.zeros((3, 3))
print(z)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [77]:
z = np.zeros((3, 4))
print(z)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [78]:
# creating matrix with data type defined as int
z = np.zeros((3, 4), dtype=np.int)
print(z)
print(z.dtype)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
int32


In [79]:
# creating all 1's matrix
o = np.ones((2, 4))
print(o)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [80]:
o = np.ones((2, 4), dtype=np.int)
print(o)

[[1 1 1 1]
 [1 1 1 1]]


In [81]:
# creating a matrix with some arbitrary number
f = np.full(shape=(3, 4), fill_value=100)
print(f)
print(f.dtype)

[[100 100 100 100]
 [100 100 100 100]
 [100 100 100 100]]
int32


In [82]:
f = np.full(shape=(1, 2), fill_value=2.0)
print(f)
print(f.dtype)

[[2. 2.]]
float64


In [83]:
# The Identity Matrix
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [84]:
np.identity(5, dtype=np.int)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

## Creating copy of Arrays

In [85]:
a = np.array([1, 2, 3])
b = a
b[0] = 100
print(a)

[100   2   3]


In [86]:
a = np.array([1, 2, 3])
b = a.copy()
b[0] = 100
print(a)

[1 2 3]


## Broadcasting in NumPy Arrays

In [90]:
a = [1, 2, 3]
print(type(a))
print(a + 1)

<class 'list'>


TypeError: can only concatenate list (not "int") to list

In [88]:
a = np.array([1, 2, 3])
print(a + 1)

[2 3 4]


In [89]:
np.random.randint(0, 100, size=(4, 5)) - 50

array([[ 40, -49, -11,  41,   5],
       [ 12, -43,  15, -33,   1],
       [-19, -45,   6, -37,   2],
       [  4, -30,  11, -21, -13]])

## Basic Mathematicall Operations 

In [97]:
# Multilication with scalar
np.random.seed(10)
A = np.random.randint(0, 100, size=(3, 4))
print(A)

[[ 9 15 64 28]
 [89 93 29  8]
 [73  0 40 36]]


In [98]:
A * 0

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [99]:
4 * A

array([[ 36,  60, 256, 112],
       [356, 372, 116,  32],
       [292,   0, 160, 144]])

In [100]:
# Division with scalar
A / 2

array([[ 4.5,  7.5, 32. , 14. ],
       [44.5, 46.5, 14.5,  4. ],
       [36.5,  0. , 20. , 18. ]])

In [101]:
A // 3

array([[ 3,  5, 21,  9],
       [29, 31,  9,  2],
       [24,  0, 13, 12]], dtype=int32)

In [102]:
A / np.array([1, 2, 3, 4])

array([[ 9.        ,  7.5       , 21.33333333,  7.        ],
       [89.        , 46.5       ,  9.66666667,  2.        ],
       [73.        ,  0.        , 13.33333333,  9.        ]])

In [104]:
A / np.random.randint(1, 5, size=(3, 4))

array([[ 2.25      , 15.        , 64.        ,  7.        ],
       [22.25      , 31.        , 29.        ,  2.        ],
       [24.33333333,  0.        , 20.        , 36.        ]])

## Matrix Operations

In [105]:
A = np.random.randint(1, 20, size=(2, 3))
print(A)

[[ 5 15 18]
 [14  6 14]]


In [106]:
B = np.random.randint(1, 20, size=(2, 3))
print(B)

[[14 13  2]
 [ 5 19 14]]


In [107]:
A + B

array([[19, 28, 20],
       [19, 25, 28]])

In [108]:
A + 2 * B

array([[33, 41, 22],
       [24, 44, 42]])

In [109]:
A - B

array([[ -9,   2,  16],
       [  9, -13,   0]])

## Element wise Operations

In [110]:
print(A)

[[ 5 15 18]
 [14  6 14]]


In [112]:
# element wise power operator
A ** 2

array([[ 25, 225, 324],
       [196,  36, 196]], dtype=int32)

In [113]:
np.sin(A)

array([[-0.95892427,  0.65028784, -0.75098725],
       [ 0.99060736, -0.2794155 ,  0.99060736]])

In [114]:
np.cos(A)

array([[ 0.28366219, -0.75968791,  0.66031671],
       [ 0.13673722,  0.96017029,  0.13673722]])

In [115]:
np.tan(A)

array([[-3.38051501, -0.8559934 , -1.13731371],
       [ 7.24460662, -0.29100619,  7.24460662]])

In [116]:
np.exp(A)

array([[1.48413159e+02, 3.26901737e+06, 6.56599691e+07],
       [1.20260428e+06, 4.03428793e+02, 1.20260428e+06]])

## Linear Algebra

In [124]:
# Taking the matrix dot products between 2 matrices
A = np.array([[1, 2]])
B = np.array([[5, 10, 0], [-9, 0, 3]])

In [125]:
print(A)

[[1 2]]


In [126]:
print(B)

[[ 5 10  0]
 [-9  0  3]]


In [127]:
R = A.dot(B)
print(R)

[[-13  10   6]]


In [128]:
print(A.shape)
print(B.shape)
print(R.shape)

(1, 2)
(2, 3)
(1, 3)


In [138]:
# Determinant of a Square Matrix
A = np.random.randint(-100, 100, size=(4, 4))
print(A)

[[-89  12 -88 -38]
 [ 85 -21   8 -58]
 [-43  -3 -50 -55]
 [ 68  65  28  46]]


In [139]:
print(np.linalg.det(A))

-11156111.99999997


In [134]:
I = np.identity(4, dtype=np.int)
print(I)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


In [135]:
print(np.linalg.det(I))

1.0


In [140]:
# Find the Trace of a Square Matrix
print(A)

[[-89  12 -88 -38]
 [ 85 -21   8 -58]
 [-43  -3 -50 -55]
 [ 68  65  28  46]]


In [141]:
print(np.trace(A))

-114


In [142]:
print(np.trace(I))

4


In [143]:
# calculating the inverse of a matrix
np.linalg.inv(I)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [145]:
A_inv = np.linalg.inv(A)
print(A_inv)

[[ 0.01749391  0.0155097  -0.02803486  0.00048727]
 [-0.01847095 -0.01248177  0.03980742  0.01659933]
 [-0.0429742  -0.02048913  0.05450089  0.00382956]
 [ 0.02639791  0.00718153 -0.04798123 -0.00476779]]


In [146]:
print(A.dot(A_inv))

[[ 1.00000000e+00 -1.59594560e-16 -1.52655666e-16  3.46944695e-18]
 [ 2.22044605e-16  1.00000000e+00  3.74700271e-16  2.42861287e-17]
 [ 0.00000000e+00 -1.21430643e-16  1.00000000e+00 -1.90819582e-17]
 [-2.22044605e-16  2.42861287e-16  2.08166817e-16  1.00000000e+00]]


In [147]:
print(A_inv.dot(A))

[[ 1.00000000e+00 -2.11961525e-17 -3.85325452e-16 -3.99094820e-16]
 [ 5.27355937e-16  1.00000000e+00  3.05311332e-16  1.80411242e-16]
 [ 3.20923843e-16 -2.38524478e-17  1.00000000e+00  1.79543880e-16]
 [-2.08166817e-17  2.25514052e-17 -3.46944695e-17  1.00000000e+00]]


In [151]:
# finding the transpose of a matrix
B = np.arange(6).reshape(2, 3)
print(B)

[[0 1 2]
 [3 4 5]]


In [152]:
print(B.shape)

(2, 3)


In [154]:
print(B.T)
print(B.T.shape)

[[0 3]
 [1 4]
 [2 5]]
(3, 2)


## Statistics

In [148]:
print(A)

[[-89  12 -88 -38]
 [ 85 -21   8 -58]
 [-43  -3 -50 -55]
 [ 68  65  28  46]]


In [149]:
# finding minimum in the matrix
np.min(A)

-89

In [150]:
# finding minimum in every column vector
np.min(A, axis=0)

array([-89, -21, -88, -58])

In [155]:
# finding the mimimum in every row vector
np.min(A, axis=1)

array([-89, -58, -55,  28])

In [156]:
# finding maximum in entire matrix
print(np.max(A))

85


In [159]:
# finding maximum in every column vector 
np.max(A, axis=0)

array([85, 65, 28, 46])

In [158]:
# finding the maximum in every row vector
np.max(A, axis=1)

array([12, 85, -3, 68])

In [160]:
# sum of every element in the matrix
np.sum(A)

-133

In [161]:
# sum of elements in every column vector
np.sum(A, axis=0)

array([  21,   53, -102, -105])

In [163]:
# sum of elements in every row vector
np.sum(A, axis=1)

array([-203,   14, -151,  207])

## Boolean Operations on Arrays

In [164]:
A = np.arange(35).reshape(5, 7)
print(A)

[[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27]
 [28 29 30 31 32 33 34]]


In [165]:
# equality check
A == 4

array([[False, False, False, False,  True, False, False],
       [False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False]])

In [166]:
# comparison operator
A < 10

array([[ True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True, False, False, False, False],
       [False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False]])

In [167]:
A >= 23

array([[False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False],
       [False, False,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True]])

In [169]:
# converting a boolean array to integer array
(A < 20).astype(np.int)

array([[1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0]])